#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "Styling"

# npm run check-types || 
# (
#     echo "Checking"
#     false;
# )

# npm run check-format || 
# (
#     echo "Checking"
#     false;
# )

# npm run check-lint || 
# (
#     echo "Checking"
#     false;
# )

echo "Checking"
